name: release-cut
on:
  schedule:
    - cron: '0 6 1 * *'
  workflow_dispatch:
jobs:
  cut:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-cut.yml@5218bc51c951148887c6a7322f553e50ad67821b # main
    secrets: inherit
