name: release-please
on:
  push:
    branches: [master]
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@main
    secrets: inherit
