name: release-security
on:
  pull_request:
    types: [closed]
jobs:
  security-release:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-security.yml@5218bc51c951148887c6a7322f553e50ad67821b # main
    secrets: inherit
